FROM python:3

LABEL maintainer = "Guilherme Muller <guilherme.muller.m@gmail.com>"

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python get-pip.py
RUN pip install click flask requests