version: '3.7'
services:
  python:
    container_name: python-container
    build: ./infra/docker/images/python
    command: python /usr/src/app/bootstrap.py
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - redis
  redis:
    container_name: redis-container
    build: ./infra/docker/images/redis
