version: '3.7'
services:
  python-daemon:
    container_name: python-daemon
    build: ./infra/docker/images/python-daemon
    command: tail -F anything
    working_dir: /usr/src/app
    ports:
      - "5000:5000"
    volumes:
      - ./src/service:/usr/src/app
      - ./datasets:/usr/datasets
    depends_on:
      - redis
  python-clt:
    container_name: python-clt
    build: ./infra/docker/images/python-clt
    command: tail -F anything
    working_dir: /usr/src/app
    volumes:
      - ./src/clt:/usr/src/app
    depends_on:
      - redis
      - python-daemon
  redis:
    container_name: redis
    build: ./infra/docker/images/redis
    volumes:
      - ./data/redis:/data
  mongodb:
    container_name: mongo
    build: ./infra/docker/images/mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  neo4j:
    container_name: neo4j
    build: ./infra/docker/images/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/var/lib/neo4j/data