version: '3'
services:
  python:
    build: ./infra/docker/images/python
    command: python /usr/src/app/bootstrap.py
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - redis
  redis:
    build: ./infra/docker/images/redis
